# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 09:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('phone', models.CharField(max_length=25, verbose_name='Phone Number')),
                ('companyName', models.CharField(max_length=100, verbose_name='Company Name')),
                ('companyAddress', models.CharField(max_length=100, verbose_name='Company Address')),
                ('companyNumber', models.CharField(max_length=8, verbose_name='Company Number')),
                ('companySector', models.CharField(choices=[('1', 'Retail'), ('2', 'Professional Services'), ('3', 'Food & Drink'), ('4', 'Entertainment')], max_length=1, verbose_name='Company Sector')),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10000), django.core.validators.MaxValueValidator(100000)], verbose_name='Amount')),
                ('duration', models.PositiveIntegerField(verbose_name='Days')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
    ]
